
package koreanfood1;

import java.awt.Image;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.ImageIcon;

public class SelectMenu extends javax.swing.JFrame {
    

    /**
     * Creates new form Three
     */

    int pricea = 0;
    int priceb = 0;
    int pricecm = 0;
    int priceo = 0;
    int priceA = 0;
    int priceC = 0;
    int priceL = 0;
    int priceCE=0;

    public SelectMenu() {
        initComponents();
        init();
    }

    
    public void init(){
        setImage();
    }
    
     public void setImage(){
        ImageIcon iconn = new ImageIcon(getClass().getResource("/image/Logo1.png"));
        
        Image imgg = iconn.getImage().getScaledInstance(Logo.getWidth(),Logo.getHeight(),Image.SCALE_SMOOTH);
        
        Logo.setIcon(new ImageIcon(imgg));
     }
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        qtySetB = new javax.swing.JSpinner();
        qtySetC = new javax.swing.JSpinner();
        qtySetA = new javax.swing.JSpinner();
        SetA = new javax.swing.JRadioButton();
        SetB = new javax.swing.JRadioButton();
        SetC = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TotalQtySet = new javax.swing.JTextField();
        TotalPriceSet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Latte = new javax.swing.JCheckBox();
        Americano = new javax.swing.JCheckBox();
        Cappucino = new javax.swing.JCheckBox();
        Chocolate = new javax.swing.JCheckBox();
        qtyAmericano = new javax.swing.JSpinner();
        qtyCappucino = new javax.swing.JSpinner();
        qtyLatte = new javax.swing.JSpinner();
        qtyChocolate = new javax.swing.JSpinner();
        SelectDrinks = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TotalQtyDrink = new javax.swing.JTextField();
        TotalDrinks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jPanel12 = new javax.swing.JPanel();
        SelectAddOns = new javax.swing.JLabel();
        sqt = new javax.swing.JCheckBox();
        Kimoli = new javax.swing.JCheckBox();
        ChickenMandu = new javax.swing.JCheckBox();
        Odeng = new javax.swing.JCheckBox();
        qtySqt = new javax.swing.JSpinner();
        qtyKimoli = new javax.swing.JSpinner();
        qtyCmd = new javax.swing.JSpinner();
        qtyOdeng = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        TotalAddOns = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalQtyAddOns = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtcn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txts = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        DineButton = new javax.swing.JRadioButton();
        TakeButton = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnc = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tot = new javax.swing.JTextField();
        SubTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Taxs = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        qtySetB.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel3.add(qtySetB);
        qtySetB.setBounds(150, 130, 60, 30);

        qtySetC.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel3.add(qtySetC);
        qtySetC.setBounds(150, 180, 60, 30);

        qtySetA.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel3.add(qtySetA);
        qtySetA.setBounds(150, 80, 60, 30);

        SetA.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(SetA);
        SetA.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        SetA.setText("SET A");
        SetA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetAActionPerformed(evt);
            }
        });
        jPanel3.add(SetA);
        SetA.setBounds(20, 80, 100, 30);

        SetB.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(SetB);
        SetB.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        SetB.setText("SET B");
        SetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetBActionPerformed(evt);
            }
        });
        jPanel3.add(SetB);
        SetB.setBounds(20, 130, 100, 30);

        SetC.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(SetC);
        SetC.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        SetC.setText("SET C");
        SetC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetCActionPerformed(evt);
            }
        });
        jPanel3.add(SetC);
        SetC.setBounds(20, 180, 100, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setBackground(new java.awt.Color(255, 153, 153));
        jLabel8.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel8.setText("SELECT YOUR SET");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(20, 10, 160, 50);

        TotalQtySet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalQtySetActionPerformed(evt);
            }
        });
        jPanel3.add(TotalQtySet);
        TotalQtySet.setBounds(20, 270, 80, 30);

        TotalPriceSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceSetActionPerformed(evt);
            }
        });
        jPanel3.add(TotalPriceSet);
        TotalPriceSet.setBounds(140, 270, 80, 30);

        jLabel2.setText("QUANTITY:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 250, 70, 16);

        jLabel4.setText("TOTAL SET:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(150, 250, 70, 16);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 230, 230, 310);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        Latte.setBackground(new java.awt.Color(204, 255, 255));
        Latte.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Latte.setText("LATTE");
        Latte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatteActionPerformed(evt);
            }
        });
        jPanel10.add(Latte);
        Latte.setBounds(25, 156, 79, 31);

        Americano.setBackground(new java.awt.Color(204, 255, 255));
        Americano.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Americano.setText("AMERICANO");
        Americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoActionPerformed(evt);
            }
        });
        jPanel10.add(Americano);
        Americano.setBounds(25, 58, 95, 31);

        Cappucino.setBackground(new java.awt.Color(204, 255, 255));
        Cappucino.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Cappucino.setText("CAPPUCINO");
        Cappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CappucinoActionPerformed(evt);
            }
        });
        jPanel10.add(Cappucino);
        Cappucino.setBounds(25, 107, 111, 30);

        Chocolate.setBackground(new java.awt.Color(204, 255, 255));
        Chocolate.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Chocolate.setText("CHOCOLATE");
        Chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateActionPerformed(evt);
            }
        });
        jPanel10.add(Chocolate);
        Chocolate.setBounds(25, 207, 95, 29);

        qtyAmericano.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel10.add(qtyAmericano);
        qtyAmericano.setBounds(150, 60, 61, 31);

        qtyCappucino.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel10.add(qtyCappucino);
        qtyCappucino.setBounds(150, 110, 61, 30);

        qtyLatte.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel10.add(qtyLatte);
        qtyLatte.setBounds(150, 160, 61, 32);

        qtyChocolate.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel10.add(qtyChocolate);
        qtyChocolate.setBounds(150, 210, 61, 30);

        SelectDrinks.setBackground(new java.awt.Color(255, 204, 51));
        SelectDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel13.setText("SELECT DRINKS");

        javax.swing.GroupLayout SelectDrinksLayout = new javax.swing.GroupLayout(SelectDrinks);
        SelectDrinks.setLayout(SelectDrinksLayout);
        SelectDrinksLayout.setHorizontalGroup(
            SelectDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        SelectDrinksLayout.setVerticalGroup(
            SelectDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(SelectDrinks);
        SelectDrinks.setBounds(40, 10, 140, 40);

        TotalQtyDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalQtyDrinkActionPerformed(evt);
            }
        });
        jPanel10.add(TotalQtyDrink);
        TotalQtyDrink.setBounds(20, 270, 80, 30);

        TotalDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDrinksActionPerformed(evt);
            }
        });
        jPanel10.add(TotalDrinks);
        TotalDrinks.setBounds(140, 270, 80, 30);

        jLabel9.setText("QUANTITY:");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(30, 250, 70, 16);

        jLabel12.setText("TOTAL DRINKS:");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(130, 250, 110, 16);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(550, 230, 230, 310);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel11.setText("SELECY YOUR SET");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jCheckBox12.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jCheckBox12.setText("SET A");

        jCheckBox13.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jCheckBox13.setText("SET B");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jCheckBox14.setText("SET C");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner12)
                            .addComponent(jSpinner13)
                            .addComponent(jSpinner14))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jCheckBox12))
                    .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox13)
                    .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox14)
                    .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(50, 310, 250, 270);

        jPanel12.setBackground(new java.awt.Color(255, 204, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SelectAddOns.setBackground(new java.awt.Color(255, 204, 0));
        SelectAddOns.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        SelectAddOns.setText("SELECT ADD-ONS");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(SelectAddOns, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectAddOns, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel12);
        jPanel12.setBounds(50, 10, 166, 34);

        sqt.setBackground(new java.awt.Color(204, 255, 255));
        sqt.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        sqt.setText("SQUID TWIGIM");
        sqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqtActionPerformed(evt);
            }
        });
        jPanel7.add(sqt);
        sqt.setBounds(40, 60, 110, 30);

        Kimoli.setBackground(new java.awt.Color(204, 255, 255));
        Kimoli.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Kimoli.setText("KIMOLI");
        Kimoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KimoliActionPerformed(evt);
            }
        });
        jPanel7.add(Kimoli);
        Kimoli.setBounds(40, 110, 85, 30);

        ChickenMandu.setBackground(new java.awt.Color(204, 255, 255));
        ChickenMandu.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        ChickenMandu.setText("CHICKEN MANDU");
        ChickenMandu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenManduActionPerformed(evt);
            }
        });
        jPanel7.add(ChickenMandu);
        ChickenMandu.setBounds(40, 160, 140, 30);

        Odeng.setBackground(new java.awt.Color(204, 255, 255));
        Odeng.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        Odeng.setText("ODENG");
        Odeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdengActionPerformed(evt);
            }
        });
        jPanel7.add(Odeng);
        Odeng.setBounds(40, 210, 80, 30);

        qtySqt.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel7.add(qtySqt);
        qtySqt.setBounds(210, 60, 60, 30);

        qtyKimoli.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel7.add(qtyKimoli);
        qtyKimoli.setBounds(210, 110, 60, 30);

        qtyCmd.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel7.add(qtyCmd);
        qtyCmd.setBounds(210, 160, 60, 30);

        qtyOdeng.setModel(new javax.swing.SpinnerNumberModel());
        jPanel7.add(qtyOdeng);
        qtyOdeng.setBounds(210, 210, 60, 30);

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(420, -280, 100, 30);

        TotalAddOns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalAddOnsActionPerformed(evt);
            }
        });
        jPanel7.add(TotalAddOns);
        TotalAddOns.setBounds(200, 270, 80, 30);

        jLabel5.setText("QUANTITY:");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(40, 250, 70, 16);

        jLabel6.setText("TOTAL ADD-ONS:");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(180, 250, 120, 16);
        jPanel7.add(TotalQtyAddOns);
        TotalQtyAddOns.setBounds(30, 270, 80, 30);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(250, 230, 290, 310);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("CUSTOMER'S NAME :");

        txtcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txts);

        jLabel1.setText("SET CHOOSEN :");

        txtorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorderActionPerformed(evt);
            }
        });

        jLabel15.setText("TYPE OF ORDER:");

        DineButton.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(DineButton);
        DineButton.setText("DINE IN");
        DineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineButtonActionPerformed(evt);
            }
        });

        TakeButton.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(TakeButton);
        TakeButton.setText("TAKE AWAY");
        TakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(TakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(DineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtorder, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DineButton))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TakeButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(360, 30, 410, 192);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 620, 80, 29);
        jPanel1.add(Logo);
        Logo.setBounds(40, 90, 130, 140);

        btnc.setText("CALCULATE");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        jPanel1.add(btnc);
        btnc.setBounds(670, 620, 100, 30);

        jButton5.setText("GENERATE RECEIPT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(890, 610, 170, 30);

        area.setBackground(new java.awt.Color(204, 255, 204));
        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(800, 20, 360, 590);

        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(340, 620, 80, 30);

        jLabel14.setText("SUBTOTAL:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(580, 560, 70, 16);

        jButton1.setText("PREVIOUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 10, 90, 30);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel3.setText("SEOUL FOOD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 370, 60);

        Tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotActionPerformed(evt);
            }
        });
        jPanel1.add(Tot);
        Tot.setBounds(680, 580, 80, 30);

        SubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalActionPerformed(evt);
            }
        });
        jPanel1.add(SubTotal);
        SubTotal.setBounds(570, 580, 90, 30);

        jLabel16.setText("TOTAL :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(690, 560, 70, 16);
        jPanel1.add(Taxs);
        Taxs.setBounds(470, 580, 80, 30);

        jLabel17.setText("TAX :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(490, 560, 48, 16);

        jButton4.setText("PRINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(560, 620, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetAActionPerformed
        // TODO add your handling code here:   
       if (SetA.isSelected())
           SetB.setSelected(false);
           SetC.setSelected(false);
           qtySetB.setValue(0);
           qtySetC.setValue(0);
           
           qtyiszero();
           
           
           txts.setText(SetA.getText());
           
           
          
    }//GEN-LAST:event_SetAActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void sqtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqtActionPerformed
        // TODO add your handling code here:
        
        if( sqt.isSelected()){
            int pricea = 0;
        }
        else{
            qtySqt.setValue(0);
        }
  
        qtyiszero2();     
    }//GEN-LAST:event_sqtActionPerformed

    private void KimoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KimoliActionPerformed
        // TODO add your handling code here:
        if( Kimoli.isSelected()){
            int priceb=0;
        }
        else{
            qtyKimoli.setValue(0);
        }
      
        qtyiszero2();
    }//GEN-LAST:event_KimoliActionPerformed

    private void ChickenManduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenManduActionPerformed
        // TODO add your handling code here:
        qtyiszero2();

        if(ChickenMandu.isSelected()){
            int pricecm = 0;
        }
        else{
            qtyCmd.setValue(0);
        }
        qtyiszero2();
        
    }//GEN-LAST:event_ChickenManduActionPerformed

    private void OdengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdengActionPerformed
        // TODO add your handling code here:
      qtyiszero2();

        if( Odeng.isSelected()){
            double priceo=6.90;
        }
        else{
            qtyOdeng.setValue(0);
        }
    }//GEN-LAST:event_OdengActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void AmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoActionPerformed
        // TODO add your handling code here:
        if(Americano.isSelected()){
            double priceA = 6.90;
        }
        else{
            qtyAmericano.setValue(0);
        }
        qtyiszero();
    }//GEN-LAST:event_AmericanoActionPerformed

    private void ChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateActionPerformed
        // TODO add your handling code here:
  
        if(Chocolate.isSelected()){
           double priceCE = 12.90;
        }
        else{
            qtyChocolate.setValue(0);
        }
        qtyiszero();
    }//GEN-LAST:event_ChocolateActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        KoreanMenu fo = new KoreanMenu();
        fo.show();

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnActionPerformed
    public void qtyiszero()
    {
        if(Integer.parseInt(qtySetA.getValue().toString())== 0)
        {
           JOptionPane.showMessageDialog(null,"Please increase the item quantity"); 
        }
    }
      public void qtyiszero2()
    {
        if(Integer.parseInt(qtySqt.getValue().toString())== 0)
        {
           JOptionPane.showMessageDialog(null,"Please increase the item quantity"); 
        }   
    }
    private void SetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetBActionPerformed
        // TODO add your handling code here:
        if (SetB.isSelected())
           SetA.setSelected(false);
           SetC.setSelected(false);
           qtySetC.setValue(0);
           qtySetA.setValue(0);

           qtyiszero();
           
           txts.setText(SetB.getText());
    }//GEN-LAST:event_SetBActionPerformed

    private void SetCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetCActionPerformed
        // TODO add your handling code here:
        if (SetC.isSelected())
           SetA.setSelected(false);
           SetB.setSelected(false);
           qtySetA.setValue(0);
           qtySetB.setValue(0);

           qtyiszero();           
           txts.setText(SetC.getText());        
    }//GEN-LAST:event_SetCActionPerformed

    private void CappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CappucinoActionPerformed
        // TODO add your handling code here:
       double price = 0;
        
        if( Cappucino.isSelected()){
            double priceC = 11;
        }
        else{
            qtyCappucino.setValue(0);
        }
        qtyiszero();
    }//GEN-LAST:event_CappucinoActionPerformed

    private void LatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatteActionPerformed
        // TODO add your handling code here:

        if(Latte.isSelected()){
            double priceL = 10;
        }
        else{
            qtyLatte.setValue(0);
        }
        qtyiszero();
    }//GEN-LAST:event_LatteActionPerformed
     
    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        double PrcSetA = 0;
        double PrcSetB = 0;
        double PrcSetC= 0;
        double PrcSqT = 0;
        double PrcKimoli = 0;
        double PrcCmd = 0;
        double PrcOdeng = 0;
        double PrcAmericano = 0;
        double PrcCappucino = 0;
        double PrcLatte = 0;
        double PrcChocolate = 0;
        double TotalAll=0;
        double Tax = 0;  
        double Subtotal = 0;
        double totalAddOnsqty = 0;
        double totalsetqty = 0;
        double TotalDrinkqty = 0;
        double TotalAddOnsPrice = 0;
        double TotalSetPrice = 0;
        double TotalDrink = 0;
        
              
        int QtySetA = 0;
        int QtySetB = 0;
        int QtySetC = 0;
        int QtySqT = 0;
        int QtyKimoli = 0;
        int QtyCmd = 0;
        int QtyOdeng = 0;
        int QtyAmericano = 0;
        int QtyCappucino = 0;
        int QtyLatte = 0;
        int QtyChocolate = 0;
        
        
        QtySetA = (int)qtySetA.getValue();
        QtySetB = (int)qtySetB.getValue();
        QtySetC = (int)qtySetC.getValue();
        QtySqT = (int)qtySqt.getValue();
        QtyKimoli = (int)qtyKimoli.getValue();
        QtyCmd = (int)qtyCmd.getValue();
        QtyOdeng= (int)qtyOdeng.getValue();
        QtyAmericano = (int)qtyAmericano.getValue();
        QtyCappucino = (int)qtyCappucino.getValue();
        QtyLatte = (int)qtyLatte.getValue();
        QtyChocolate = (int)qtyChocolate.getValue();
        
        
        if(txtcn.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null,"Please put your name");
        }
        
        if(SetA.isSelected())
        {
            PrcSetA= 24.00*QtySetA;
        }
        if(SetB.isSelected())
        {
            PrcSetB = 25.00*QtySetB;
        }
        if(SetC.isSelected())
        {  
            PrcSetC=26.00*QtySetC;    
        }
        
        if (sqt.isSelected())
        {
            PrcSqT=7.90*QtySqT;
        }
        
        if (Kimoli.isSelected())
        {
            PrcKimoli=5.90*QtyKimoli;
        }
        
        if (ChickenMandu.isSelected())
        {
            PrcCmd=2.90*QtyCmd;
        }
        
        if (Odeng.isSelected())
        {
            PrcOdeng=6.90*QtyOdeng;
        }
        if (Americano.isSelected())
        {
            PrcAmericano=6.90*QtyAmericano;
        }
        if (Cappucino.isSelected())
        {
            PrcCappucino=10.90*QtyCappucino;
        }
        if (Latte.isSelected())
        {
            PrcLatte=9.90*QtyLatte;
        }
        if (Chocolate.isSelected())
        {
            PrcChocolate=12.90*QtyChocolate;
        }   
        
 
        
        {
        totalsetqty = QtySetA + QtySetB + QtySetC;
        SelectMenu.TotalQtySet.setText(Double.toString(totalsetqty));
        
        TotalSetPrice=PrcSetA + PrcSetB + PrcSetC;
        SelectMenu.TotalPriceSet.setText(Double.toString(TotalSetPrice));
        TotalPriceSet.setText("RM" + String.format("%.2f",TotalSetPrice));
        }
        
        {
        totalAddOnsqty=QtySqT + QtyKimoli + QtyCmd + QtyOdeng;
        SelectMenu.TotalQtyAddOns.setText(Double.toString(totalAddOnsqty));
       
        TotalAddOnsPrice = PrcSqT + PrcKimoli + PrcCmd + PrcOdeng;
        TotalAddOns.setText("RM" + String.format("%.2f",TotalAddOnsPrice));
        }
        
        {
        TotalDrinkqty = QtyAmericano + QtyCappucino + QtyLatte + QtyChocolate;
        SelectMenu.TotalQtyDrink.setText(Double.toString(TotalDrinkqty));
        
        TotalDrink = PrcAmericano + PrcCappucino + PrcLatte + PrcChocolate;
        TotalDrinks.setText("RM" + String.format("%.2f",TotalDrink));

        }
        
        TotalAll =PrcSetA + PrcSetB + PrcSetC + PrcSqT + PrcKimoli + PrcCmd + PrcOdeng + PrcAmericano + PrcCappucino + PrcLatte + PrcChocolate;
        Subtotal = TotalAll;
        Tax = 0.05 * Subtotal;
        double Total = Tax + Subtotal;
        
        
       Tot.setText("RM" + String.format("%.2f",Total));
       SubTotal.setText("RM" + String.format("%.2f",Subtotal));
       Taxs.setText("RM" + String.format("%.2f",Tax));
   
        
       
       
                
        
  
        
         
    }//GEN-LAST:event_btncActionPerformed

    private void TotalQtySetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalQtySetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TotalQtySetActionPerformed

    private void TotalQtyDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalQtyDrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalQtyDrinkActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Date obj = new Date ();
        String date = obj.toString();

        area.setText("**********************************************************\n");  
        area.setText(area.getText() + "Welcome ("+txtcn.getText()+") to Korean Restaurant\n"); 
        area.setText(area.getText() + "**********************************************************\n"); 
        area.setText(area.getText() + "" + date + "\n\n");
        area.setText(area.getText() + "Customer's Name    : " + txtcn.getText() + "\n\n");
        area.setText(area.getText() + "Type of Order       : " + txtorder.getText() + "\n\n");   
        area.setText(area.getText() + "**********************************************************\n");
        area.setText(area.getText() + "Set                 : " + txts.getText() + "\n\n");
        area.setText(area.getText() + "Set Quantity        : " + TotalQtySet.getText() + "\n\n"); 
        area.setText(area.getText() + "Total Price Set     : " + TotalPriceSet.getText()+"\n\n"  );
        area.setText(area.getText() + "**********************************************************\n");
        area.setText(area.getText()+  "Addons Quantity    : "+TotalQtyAddOns.getText()+"\n\n");
        area.setText(area.getText()+  "Total Price AddOns : "+TotalAddOns.getText()+"\n\n");
        area.setText(area.getText() + "**********************************************************\n");
        area.setText(area.getText()+  "Drink Quantity     : "+TotalQtyDrink.getText()+"\n\n");
        area.setText(area.getText()+  "Total Price Drink  : "+TotalDrinks.getText()+"\n\n");
        area.setText(area.getText() + "*****************************************\n");
        area.setText(area.getText()+  "Subtotal : "+SubTotal.getText()+"\n\n");
        area.setText(area.getText()+  "Tax : "+ Taxs.getText() + "\n\n");
        area.setText(area.getText()+  "Total : "+ Tot.getText()+ "\n\n");
        area.setText(area.getText() + "*****************************************\n");
        area.setText(area.getText() + "Thank you for choosing us!Please come again next time");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TotalPriceSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceSetActionPerformed

    private void TotalDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalDrinksActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           TotalQtySet.setText(null);
           
           txtorder.setText(null);
           TotalPriceSet.setText(null);
           TotalAddOns.setText(null);
           TotalQtyAddOns.setText(null);
           TotalQtyDrink.setText(null);
           TotalDrinks.setText(null);
           Tot.setText(null);
           Taxs.setText(null);
           SubTotal.setText(null);
           txtcn.setText(null);
           txts.setText(null);
           sqt.setSelected(false);
           Kimoli.setSelected(false);
           ChickenMandu.setSelected(false);
           Odeng.setSelected(false); 
           Americano.setSelected(false);
           Cappucino.setSelected(false);
           Latte.setSelected(false);
           Chocolate.setSelected(false);
           SetA.setSelected(false);
           SetB.setSelected(false);
           SetC.setSelected(false);
           qtySetA.setValue(0);
           qtySetB.setValue(0);
           qtySqt.setValue(0);          
           qtyKimoli.setValue(0);
           qtyCmd.setValue(0);
           qtyOdeng.setValue(0);
           qtyAmericano.setValue(0);
           qtyCappucino.setValue(0);
           qtyLatte.setValue(0);
           qtyChocolate.setValue(0);
           area.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeButtonActionPerformed
        // TODO add your handling code here:
        if (TakeButton.isSelected())
           DineButton.setSelected(false);
      
          SelectMenu.txtorder.setText(TakeButton.getText());

    }//GEN-LAST:event_TakeButtonActionPerformed

    private void DineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineButtonActionPerformed
        // TODO add your handling code here:
        if (DineButton.isSelected())
           TakeButton.setSelected(false);
        
        SelectMenu.txtorder.setText(DineButton.getText());

    }//GEN-LAST:event_DineButtonActionPerformed

    private void txtorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalActionPerformed

    private void TotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotActionPerformed

    private void TotalAddOnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalAddOnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalAddOnsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
             area.print();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        SelectMenu f2 = new SelectMenu();
        f2.show();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JCheckBox Americano;
    javax.swing.JCheckBox Cappucino;
    javax.swing.JCheckBox ChickenMandu;
    javax.swing.JCheckBox Chocolate;
    javax.swing.JRadioButton DineButton;
    javax.swing.JCheckBox Kimoli;
    javax.swing.JCheckBox Latte;
    javax.swing.JLabel Logo;
    javax.swing.JCheckBox Odeng;
    javax.swing.JLabel SelectAddOns;
    javax.swing.JPanel SelectDrinks;
    javax.swing.JRadioButton SetA;
    javax.swing.JRadioButton SetB;
    javax.swing.JRadioButton SetC;
    static javax.swing.JTextField SubTotal;
    javax.swing.JRadioButton TakeButton;
    static javax.swing.JTextField Taxs;
    static javax.swing.JTextField Tot;
    static javax.swing.JTextField TotalAddOns;
    static javax.swing.JTextField TotalDrinks;
    static javax.swing.JTextField TotalPriceSet;
    static javax.swing.JTextField TotalQtyAddOns;
    static javax.swing.JTextField TotalQtyDrink;
    static javax.swing.JTextField TotalQtySet;
    javax.swing.JTextArea area;
    javax.swing.JButton btnc;
    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.ButtonGroup buttonGroup2;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JButton jButton5;
    javax.swing.JButton jButton6;
    javax.swing.JCheckBox jCheckBox12;
    javax.swing.JCheckBox jCheckBox13;
    javax.swing.JCheckBox jCheckBox14;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel10;
    javax.swing.JPanel jPanel12;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JSpinner jSpinner12;
    javax.swing.JSpinner jSpinner13;
    javax.swing.JSpinner jSpinner14;
    javax.swing.JSpinner qtyAmericano;
    javax.swing.JSpinner qtyCappucino;
    javax.swing.JSpinner qtyChocolate;
    javax.swing.JSpinner qtyCmd;
    javax.swing.JSpinner qtyKimoli;
    javax.swing.JSpinner qtyLatte;
    javax.swing.JSpinner qtyOdeng;
    javax.swing.JSpinner qtySetA;
    javax.swing.JSpinner qtySetB;
    javax.swing.JSpinner qtySetC;
    public static javax.swing.JSpinner qtySqt;
    javax.swing.JCheckBox sqt;
    javax.swing.JTextField txtcn;
    static javax.swing.JTextField txtorder;
    public static javax.swing.JTextPane txts;
    // End of variables declaration//GEN-END:variables

    private Object getValue() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}


